name: nobibot
description: NobiBot.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  theme_mode_handler: ^3.0.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3

  retrofit: ">=3.0.0 <4.0.0"
  logger: any
  flip_card: ^0.6.0
  page_transition: ^2.0.5
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  retrofit_generator: ">=4.0.0 <5.0.0"
  build_runner: ">2.0.0 <4.0.0"
  json_serializable: ">4.4.0"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazir.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 700
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 900
